### ISSUE TITLE
Updated targets

### ISSUE THREAD

**Issue by kathsherratt** [covid19-forecast-hub-europe/covid19-scenario-hub-europe#24]
New targets to include:

- generic or average European location - `Hypothetical` with code `H0`
- infections target - `inc infection` (singular to match `inc case`, `inc death`)
- ICU admissions target - `inc hosp_icu`

Update :
-  [ ] `location` csv
-  [ ] hub schema yaml
-  [x] Wiki

**Comment by kathsherratt** [comment]
Similarly, for Round 1 we need to check the csv validation is adapted to use sample numbers rather than quantiles (unless this is already in place).

**Comment by Bisaloo** [comment]
Fixed in #25
